---
__Universidad Tecnológica Nacional, Buenos Aires__\
__Ingeniería Industrial__\
__Cátedra de Investigación Operativa__\
__Autor: Rodrigo Maranzana__, Rmaranzana@frba.utn.edu.ar

---

# Ejercicios Markov clase 4

In [ ]:
import numpy as np

## Ejercicio 4
Suponga que toda la industria de refresco produce dos colas: Coca Cola y Pepsi Cola. Cuando una persona ha comprado Coca Cola hay una probabilidad de 90% de que siga comprándola la vez siguiente. Si una persona compró Pepsi, hay 80% de que repita la vez siguiente. Se pide: 

a) Si una persona actualmente es comprador de Pepsi. ¿Cuál es la probabilidad de que compre Coca Cola pasadas dos compras a partir de hoy?

b) Si en la actualidad una persona es comprador de Coca Cola. ¿Cuál es la probabilidad de que compre Coca Cola pasadas tres compras a partir de ahora?

c) Supongamos que el 60% de toda la gente toma hoy Coca Cola y el 40% Pepsi. A tres compras a partir de ahora, ¿Qué fracción de los compradores estará tomando Coca Cola.

d) Determinar el estado estacionario.


In [169]:
# Ingresamos la matriz de transición como matriz de numpy:
T = np.array([[0.9, 0.1], [0.2, 0.8]])
print('La matriz de transición: \n %s' %T)

La matriz de transición: 
 [[0.9 0.1]
 [0.2 0.8]]


### 4.a

In [170]:
# Calculamos la matriz de transición a tiempo 2 elevando T al cuadrado:
T_2 = np.linalg.matrix_power(T, 2)
print('La matriz de transición a t=2: \n %s \n' %T_2)

# El elemento matemático (2, 1), es decir (1, 0) en los índices de python es la probabilidad de pasar de Pepsi
# a Coca Cola en 2 iteraciones:
p_pc2 = T_2[1, 0]
print('La probabilidad de pasar de pepsi a coca cola en t=2: %0.5f' %p_pc2)

La matriz de transición a t=2: 
 [[0.83 0.17]
 [0.34 0.66]] 

La probabilidad de pasar de pepsi a coca cola en t=2: 0.34000


### 4.b

In [171]:
# Calculamos la matriz de transición a tiempo 3 elevando T al cubo:
T_3 = np.linalg.matrix_power(T, 3)
print('La matriz de transición a t=3: \n %s \n' %T_3)

# El elemento matemático (1, 1), es decir (0, 0) en los índices de python es la probabilidad de quedar
# en coca cola luego de 3 iteraciones:
p_cc3 = T_3[0, 0]
print('La probabilidad quedarse en cocacola a t=3: %0.5f' %p_cc3)

La matriz de transición a t=3: 
 [[0.781 0.219]
 [0.438 0.562]] 

La probabilidad quedarse en cocacola a t=3: 0.78100


### 4.c

In [172]:
# Ingresamos el vector de estado a tiempo 0:
p_0 = np.array([0.6, 0.4])
print('Vector de probabilidades iniciales: \n %s \n' %p_0)

# Calculamos el vector de estado a tiempo 3 siguiendo la fórmula p_3 = p_0 x T^3
p_3 = np.dot(p_0, T_3)
print('Vector de probabilidades a t=3: \n %s \n' %p_3)

# La probabilidad de estar en cocacola en 3 iteraciones es el primer elemento del vector de estado:
p_c3 = p_3[0]
print('Probabilidad de estar en coca cola a t=3 dado vector inicial: \n %0.5f \n' %p_c3)

Vector de probabilidades iniciales: 
 [0.6 0.4] 

Vector de probabilidades a t=3: 
 [0.6438 0.3562] 

Probabilidad de estar en coca cola a t=3 dado vector inicial: 
 0.64380 



### 4.d 

In [173]:
# Ingresamos los datos para calcular AX = B
A = np.array([[-0.1, 0.2], [0.1, -0.2], [1, 1]])
print('Matriz A relacionada al sistema lineal de ecauciones: \n %s \n' %A)

B = np.array([0, 0, 1])
print('Vector B relacionado al sistema lineal de ecuaciones: \n %s \n' %B)

# Resolvemos por mínimos cuadrados:
X, _, _, _ = np.linalg.lstsq(A, B)
print('Solución del sistema lineal de ecuaciones: \n %s \n' %X)

Matriz A relacionada al sistema lineal de ecauciones: 
 [[-0.1  0.2]
 [ 0.1 -0.2]
 [ 1.   1. ]] 

Vector B relacionado al sistema lineal de ecuaciones: 
 [0 0 1] 

Solución del sistema lineal de ecuaciones: 
 [0.66666667 0.33333333] 



c:\users\m_a_r\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


## Ejercicio 5
La cervecería más importante del mundo (Guiness) ha contratado a un analista de investigación de operaciones para analizar su posición en el mercado. Están preocupados en especial por su mayor competidor (Heineken). El analista piensa que el cambio de marca se puede modelar como una cadena de Markov incluyendo tres estados, los estados G y H representan a los clientes que beben cerveza producida por las mencionadas cervecerías y el estado I representa todas las demás marcas. Los datos se toman cada mes y el analista ha construido la siguiente matriz de transición de los datos históricos.

| /| G | H  | I  |
|--:|--:|---:|---:|
| G |0.7|0.2 |0.1 |
| H |0.2|0.75|0.05|
| I |0.1|0.1 |0.8 |


In [174]:
# Ingresamos la matriz de transición:
T = np.array([[0.7, 0.2, 0.1], [0.2, 0.75, 0.05], [0.1, 0.1, 0.8]])
print('Matriz de transición: \n %s \n' %T)

Matriz de transición: 
 [[0.7  0.2  0.1 ]
 [0.2  0.75 0.05]
 [0.1  0.1  0.8 ]] 



In [175]:
# Construir matriz A y vector B:
A = (np.transpose(T) - np.identity(3))
print('Matriz A relacionada al sistema lineal de ecauciones: \n %s \n' %A)
B = np.zeros(3)
print('Vector B relacionado al sistema lineal de ecuaciones: \n %s \n' %B)

# Agregar sumatoria de probabilidades:
adicional = np.array([[1, 1, 1]])
A = np.concatenate((A, adicional), axis=0)
print('Matriz A: \n %s \n' %A)
B = np.append(B, 1)
print('Vector B: \n %s \n' %B)

Matriz A relacionada al sistema lineal de ecauciones: 
 [[-0.3   0.2   0.1 ]
 [ 0.2  -0.25  0.1 ]
 [ 0.1   0.05 -0.2 ]] 

Vector B relacionado al sistema lineal de ecuaciones: 
 [0. 0. 0.] 

Matriz A: 
 [[-0.3   0.2   0.1 ]
 [ 0.2  -0.25  0.1 ]
 [ 0.1   0.05 -0.2 ]
 [ 1.    1.    1.  ]] 

Vector B: 
 [0. 0. 0. 1.] 



In [176]:
# Resolvemos por mínimos cuadrados:
X, _, _, _ = np.linalg.lstsq(A, B)
print('Solución del sistema lineal de ecuaciones: \n %s \n' %X)

Solución del sistema lineal de ecuaciones: 
 [0.34615385 0.38461538 0.26923077] 



c:\users\m_a_r\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


## Ejercicio 6
En una comunidad hay 3 supermercados (S1, S2, S3) existe la movilidad de un cliente de uno a otro. El 1 de septiembre, 1⁄4 de los clientes va al S1, 1/3 al S2 y 5/12 al S3 de un total de 10.000 personas. Cada mes el S1 retiene el 90% de sus clientes y pierde el 10% que se va al S2. Se averiguó que el S2 solo retiene el 5% y pierde el 85% que va a S1 y el resto se va a S3, el S3 retiene solo el 40%, pierde el 50% que va al S1 y el 10% va al S2.

a) Establecer la matriz de transición

b) ¿Cuál es la proporción de clientes para los supermercados el 1 de noviembre?

c) Hallar el vector de probabilidad estable.

### 6.a

In [177]:
# Ingresamos la matriz de transición:
T = np.array([[0.9, 0.1, 0], [0.85, 0.05, 0.1], [0.5, 0.1, 0.4]])
print('Matriz de transición: \n %s \n' %T)

# Ingresamos el vector de estado en septiembre:
p_sept = np.array([1/4, 1/3, 5/12])
print('Vector de estado de probabilidades en septiembre: \n %s \n' %p_sept)

Matriz de transición: 
 [[0.9  0.1  0.  ]
 [0.85 0.05 0.1 ]
 [0.5  0.1  0.4 ]] 

Vector de estado de probabilidades en septiembre: 
 [0.25       0.33333333 0.41666667] 



### 6.b

In [182]:
# Calculamos la matriz de transición en T=2 elevando T al cuadrado:
T_2 = np.linalg.matrix_power(T, 2)
print('Matriz de transición a t=2: \n %s \n' %T_2)

# Calculamos el vector de estado en noviembre: p_nov = p_sept x T^2
p_nov = np.dot(p_sept, T_2)
print('Vector de estado de probabilidades en noviembre: \n %s \n' %p_nov)

Matriz de transición a t=2: 
 [[0.895  0.095  0.01  ]
 [0.8575 0.0975 0.045 ]
 [0.735  0.095  0.17  ]] 

Vector de estado de probabilidades en noviembre: 
 [0.81583333 0.09583333 0.08833333] 



### 6.d

In [179]:
# Ingresamos los datos para calcular AX = B
A = np.array([[-0.1, 0.85, 0.5], [0.1, -0.95, 0.1], [0, 0.1, -0.6], [1, 1, 1]])
print('Matriz A relacionada al sistema lineal de ecauciones: \n %s \n' %A)

B = np.array([0, 0, 0, 1])
print('Vector B relacionado al sistema lineal de ecuaciones: \n %s \n' %B)

Matriz A relacionada al sistema lineal de ecauciones: 
 [[-0.1   0.85  0.5 ]
 [ 0.1  -0.95  0.1 ]
 [ 0.    0.1  -0.6 ]
 [ 1.    1.    1.  ]] 

Vector B relacionado al sistema lineal de ecuaciones: 
 [0 0 0 1] 



In [180]:
# Se decide usar el método np.linalg.solve de numpy, por lo tanto la matriz debe ser cuadrada.
# Eliminamos la primera fila de la matriz A y el primer elemento del vector B.
# Finalmente, comprobamos que las dimensiones sean correctas.
A = np.delete(A, 0, axis=0)
print('Matriz A: \n %s' %A)
dimension_A = A.shape
print('Dimensión: \n %s \n' %str(dimension_A))

B = np.delete(B, 0, axis=0)
print('Vector B: \n %s' %B)
dimension_B = B.shape
print('Dimensión: \n %s \n' %str(dimension_B))

# Resolvemos:
X = np.linalg.solve(A, B)
print('Solución del sistema lineal de ecuaciones: \n %s \n' %X)

Matriz A: 
 [[ 0.1  -0.95  0.1 ]
 [ 0.    0.1  -0.6 ]
 [ 1.    1.    1.  ]]
Dimensión: 
 (3, 3) 

Vector B: 
 [0 0 1]
Dimensión: 
 (3,) 

Solución del sistema lineal de ecuaciones: 
 [0.88888889 0.0952381  0.01587302] 

