---
__Universidad Tecnológica Nacional, Buenos Aires__\
__Ingeniería Industrial__\
__Cátedra de Investigación Operativa__\
__Autor: Rodrigo Maranzana__, Rmaranzana@frba.utn.edu.ar

---

# Ejemplo de Transporte con Programación Matemática
Se busca transportar por arcos que unen nodos proveedores con nodos clientes, una cantidad determinada de un solo producto. La oferta y demanda de los clientes está balanceada.

In [1]:
import numpy as np
from scipy.optimize import linprog

## Datos del ejemplo
El ejemplo está representado por:
- Una matriz Nodo-Arco.
- Un vector de pesos o costos de los arcos.
- Un vector de oferta y demanda.
- Cotas

In [2]:
# Matriz nodo-arco:
Aeq = np.array([[ 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                [ 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
                [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
                [-1, 0, 0, 0,-1, 0, 0, 0,-1, 0, 0, 0],
                [ 0,-1, 0, 0, 0,-1, 0, 0, 0,-1, 0, 0],
                [ 0, 0,-1, 0, 0, 0,-1, 0, 0, 0,-1, 0],
                [ 0, 0, 0,-1, 0, 0, 0,-1, 0, 0, 0,-1]])

# Vector de costos por arco:
C = np.array([434, 523, 640, 850, 323, 480, 670, 770, 997, 680, 390, 590])

# Vector de oferta y demanda:
beq = np.array([75, 100, 125, -80, -70, -70, -80])

# Cotas:
bounds = tuple([(0, None) for arcs in range(0, C.shape[0])])

# Imprimimos:
print('Matriz Nodo-Arco \n', Aeq,'\n')
print('Costos \n', C,'\n')
print('Oferta/Demanda \n', beq,'\n')
print('Cotas \n', bounds,'\n')

Matriz Nodo-Arco 
 [[ 1  1  1  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  1  1  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  1  1]
 [-1  0  0  0 -1  0  0  0 -1  0  0  0]
 [ 0 -1  0  0  0 -1  0  0  0 -1  0  0]
 [ 0  0 -1  0  0  0 -1  0  0  0 -1  0]
 [ 0  0  0 -1  0  0  0 -1  0  0  0 -1]] 

Costos 
 [434 523 640 850 323 480 670 770 997 680 390 590] 

Oferta/Demanda 
 [ 75 100 125 -80 -70 -70 -80] 

Cotas 
 ((0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)) 



## Optimizamos con scipy

In [3]:
# Optimizamos:
res = linprog(C, A_eq=Aeq, b_eq=beq, bounds=bounds)

## Imprimimos los resultados

In [4]:
print('Cantidad para cada arco:', res.x)
print('Costo mínimo total:', res.fun)

Cantidad para cada arco: [ 0. 70.  5.  0. 80.  0.  0. 20.  0.  0. 65. 60.]
Costo mínimo total: 141800.0
