---
__Universidad Tecnológica Nacional, Buenos Aires__\
__Ingeniería Industrial__\
__Cátedra de Investigación Operativa__\
__Autor: Rodrigo Maranzana__, Rmaranzana@frba.utn.edu.ar

---

In [8]:
#TESTING

# Ingresamos la matriz de transición:
T = np.array([[0.1, 0.3, 0.6], [0.2, 0.2, 0.6], [0.2, 0.4, 0.4]])
print('Matriz de transición: \n %s \n' %T)


# Construir matriz A y vector B:
A = (np.transpose(T) - np.identity(3))
print('Matriz A relacionada al sistema lineal de ecauciones: \n %s \n' %A)
B = np.zeros(3)
print('Vector B relacionado al sistema lineal de ecuaciones: \n %s \n' %B)

# Agregar sumatoria de probabilidades:
adicional = np.array([[1, 1, 1]])
A = np.concatenate((A, adicional), axis=0)


B = np.append(B, 1)


A = np.delete(A, 2, 0)
B = np.delete(B, 2, 0)
print('Matriz A: \n %s \n' %A)
print('Vector B: \n %s \n' %B)

# Resolvemos por mínimos cuadrados:
X, _, _, _ = np.linalg.lstsq(A, B)
print('Solución del sistema lineal de ecuaciones: \n %s \n' %X)

Matriz de transición: 
 [[0.1 0.3 0.6]
 [0.2 0.2 0.6]
 [0.2 0.4 0.4]] 

Matriz A relacionada al sistema lineal de ecauciones: 
 [[-0.9  0.2  0.2]
 [ 0.3 -0.8  0.4]
 [ 0.6  0.6 -0.6]] 

Vector B relacionado al sistema lineal de ecuaciones: 
 [0. 0. 0.] 

Matriz A: 
 [[-0.9  0.2  0.2]
 [ 0.3 -0.8  0.4]
 [ 1.   1.   1. ]] 

Vector B: 
 [0. 0. 1.] 

Solución del sistema lineal de ecuaciones: 
 [0.18181818 0.31818182 0.5       ] 



c:\users\m_a_r\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:28: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


In [4]:
print(4/17)
print(8/17)
5/17

0.23529411764705882
0.47058823529411764


0.29411764705882354

In [2]:
[0.18181818 0.31818182 0.5] 

 [0.18181818 0.31818182 0.5       ] 


SyntaxError: invalid syntax (<ipython-input-2-f1ecaa148c22>, line 1)